# -------------------------------------------------------
# variables.tf — Input variables for the Nginx deployment
# -------------------------------------------------------

variable "aws_region" {
  description = "AWS region to deploy resources in"
  type        = string
}

variable "instance_type" {
  description = "EC2 instance type"
  type        = string
}

variable "key_name" {
  description = "Name to assign to the AWS key pair resource"
  type        = string
}

variable "public_key_path" {
  description = "Path to your LOCAL RSA public key file (generated by ssh-keygen)"
  type        = string
}

variable "state_bucket_name" {
  description = "Globally unique S3 bucket name for storing Terraform remote state"
  type        = string
}

variable "dynamodb_table_name" {
  description = "DynamoDB table name used for Terraform state locking"
  type        = string
}

variable "html_title" {
  description = "Title shown in the browser tab for the Nginx page"
  type        = string
}

variable "html_body" {
  description = "HTML body content injected into the Nginx index page"
  type        = string
}